# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Vitorlevi"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = ""
homepage = "http://siteforthistheme.com/"
tags = []
features = []
min_version = "0.20.7"

[author]
  name = "Vitor Levi da Silveira"
  homepage = "http://vitorlevi.work"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
